services:
  postgres:
    image: postgres:18
    environment:
      POSTGRES_DB: bigbucks
      POSTGRES_USER: bigbucks
      POSTGRES_PASSWORD: bigbucks
    ports:
      - "6432:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U bigbucks"]
      interval: 5s
      timeout: 5s
      retries: 5

  redis:
    image: redis:8.4
    ports:
      - "6379:6379"
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 5s
      timeout: 3s
      retries: 5

  migration:
    image: ghcr.io/bigbucks-solutions/auth:0.1.7
    depends_on:
      postgres:
        condition: service_healthy
    volumes:
      - ./config.docker.json:/app/config.json:ro
      - ./ec_private.pem:/app/ec_private.pem:ro
      - ./ec_public.pem:/app/ec_public.pem:ro
    command: ["./auth", "-c", "config.json", "migrate", "up"]
    restart: on-failure

  auth:
    image: ghcr.io/bigbucks-solutions/auth:0.1.7
    depends_on:
      postgres:
        condition: service_healthy
      redis:
        condition: service_healthy
      migration:
        condition: service_completed_successfully
    ports:
      - "9000:9000"
    volumes:
      - ./config.docker.json:/app/config.json:ro
      - ./ec_private.pem:/app/ec_private.pem:ro
      - ./ec_public.pem:/app/ec_public.pem:ro
    command: ["./auth", "-c", "config.json"]
    restart: unless-stopped

volumes:
  postgres_data:
