site_name: Auth Docs

nav:
  - Home: index.markdown
  - Usage: usage.md
  - REST API: rest_api.md
  - Contrib:
      - Subscribers:
        - Stripe:
          - Overview: contrib/subscribers/stripe/index.md
          - Billing frontend: contrib/subscribers/stripe/billing-frontend.md

plugins:
  - search
  - neoteroi.mkdocsoad:
      use_pymdownx: true
      source_dir: docs
  - exclude:
      glob:
        - v3/*


markdown_extensions:
  - pymdownx.details
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_code_format
  - pymdownx.tabbed:
      alternate_style: true

# theme:


theme:
  features:
    - navigation.instant
    - navigation.tracking
    - navigation.tabs
    - navigation.tabs.sticky
    - toc.integrate
    - navigation.top
  name: material
  palette:


    # Palette toggle for light mode
    - scheme: default
      primary: 673AB7
      toggle:
        icon: material/brightness-7
        name: Switch to dark mode

    # Palette toggle for dark mode
    - scheme: slate
      primary: 673AB7
      toggle:
        icon: material/brightness-4
        name: Switch to light mode

extra_css:
  - css/neoteroi-mkdocs.css
  - css/extras.css
