// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v3.21.7
// source: grpc-auth/authorize.proto

package grpc_auth

import (
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"

	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type AuthorizeRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Resource      string                 `protobuf:"bytes,1,opt,name=resource,proto3" json:"resource,omitempty"`
	Scope         string                 `protobuf:"bytes,2,opt,name=scope,proto3" json:"scope,omitempty"`
	Action        string                 `protobuf:"bytes,3,opt,name=action,proto3" json:"action,omitempty"`
	OrgId         string                 `protobuf:"bytes,4,opt,name=org_id,json=orgId,proto3" json:"org_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AuthorizeRequest) Reset() {
	*x = AuthorizeRequest{}
	mi := &file_grpc_auth_authorize_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AuthorizeRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AuthorizeRequest) ProtoMessage() {}

func (x *AuthorizeRequest) ProtoReflect() protoreflect.Message {
	mi := &file_grpc_auth_authorize_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AuthorizeRequest.ProtoReflect.Descriptor instead.
func (*AuthorizeRequest) Descriptor() ([]byte, []int) {
	return file_grpc_auth_authorize_proto_rawDescGZIP(), []int{0}
}

func (x *AuthorizeRequest) GetResource() string {
	if x != nil {
		return x.Resource
	}
	return ""
}

func (x *AuthorizeRequest) GetScope() string {
	if x != nil {
		return x.Scope
	}
	return ""
}

func (x *AuthorizeRequest) GetAction() string {
	if x != nil {
		return x.Action
	}
	return ""
}

func (x *AuthorizeRequest) GetOrgId() string {
	if x != nil {
		return x.OrgId
	}
	return ""
}

type PermissionDetail struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Resource      string                 `protobuf:"bytes,1,opt,name=resource,proto3" json:"resource,omitempty"`
	Scope         string                 `protobuf:"bytes,2,opt,name=scope,proto3" json:"scope,omitempty"`
	Action        string                 `protobuf:"bytes,3,opt,name=action,proto3" json:"action,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PermissionDetail) Reset() {
	*x = PermissionDetail{}
	mi := &file_grpc_auth_authorize_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PermissionDetail) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PermissionDetail) ProtoMessage() {}

func (x *PermissionDetail) ProtoReflect() protoreflect.Message {
	mi := &file_grpc_auth_authorize_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PermissionDetail.ProtoReflect.Descriptor instead.
func (*PermissionDetail) Descriptor() ([]byte, []int) {
	return file_grpc_auth_authorize_proto_rawDescGZIP(), []int{1}
}

func (x *PermissionDetail) GetResource() string {
	if x != nil {
		return x.Resource
	}
	return ""
}

func (x *PermissionDetail) GetScope() string {
	if x != nil {
		return x.Scope
	}
	return ""
}

func (x *PermissionDetail) GetAction() string {
	if x != nil {
		return x.Action
	}
	return ""
}

type AuthorizeResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Result        bool                   `protobuf:"varint,1,opt,name=result,proto3" json:"result,omitempty"`
	Permitted     *PermissionDetail      `protobuf:"bytes,2,opt,name=permitted,proto3" json:"permitted,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AuthorizeResponse) Reset() {
	*x = AuthorizeResponse{}
	mi := &file_grpc_auth_authorize_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AuthorizeResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AuthorizeResponse) ProtoMessage() {}

func (x *AuthorizeResponse) ProtoReflect() protoreflect.Message {
	mi := &file_grpc_auth_authorize_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AuthorizeResponse.ProtoReflect.Descriptor instead.
func (*AuthorizeResponse) Descriptor() ([]byte, []int) {
	return file_grpc_auth_authorize_proto_rawDescGZIP(), []int{2}
}

func (x *AuthorizeResponse) GetResult() bool {
	if x != nil {
		return x.Result
	}
	return false
}

func (x *AuthorizeResponse) GetPermitted() *PermissionDetail {
	if x != nil {
		return x.Permitted
	}
	return nil
}

// AuthenticateRequest is empty — the JWT is provided via the
// "authorization" metadata header and validated by the interceptor.
type AuthenticateRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AuthenticateRequest) Reset() {
	*x = AuthenticateRequest{}
	mi := &file_grpc_auth_authorize_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AuthenticateRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AuthenticateRequest) ProtoMessage() {}

func (x *AuthenticateRequest) ProtoReflect() protoreflect.Message {
	mi := &file_grpc_auth_authorize_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AuthenticateRequest.ProtoReflect.Descriptor instead.
func (*AuthenticateRequest) Descriptor() ([]byte, []int) {
	return file_grpc_auth_authorize_proto_rawDescGZIP(), []int{3}
}

type AuthenticateResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        string                 `protobuf:"bytes,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	Username      string                 `protobuf:"bytes,2,opt,name=username,proto3" json:"username,omitempty"`
	Roles         []*UserOrgRole         `protobuf:"bytes,3,rep,name=roles,proto3" json:"roles,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AuthenticateResponse) Reset() {
	*x = AuthenticateResponse{}
	mi := &file_grpc_auth_authorize_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AuthenticateResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AuthenticateResponse) ProtoMessage() {}

func (x *AuthenticateResponse) ProtoReflect() protoreflect.Message {
	mi := &file_grpc_auth_authorize_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AuthenticateResponse.ProtoReflect.Descriptor instead.
func (*AuthenticateResponse) Descriptor() ([]byte, []int) {
	return file_grpc_auth_authorize_proto_rawDescGZIP(), []int{4}
}

func (x *AuthenticateResponse) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *AuthenticateResponse) GetUsername() string {
	if x != nil {
		return x.Username
	}
	return ""
}

func (x *AuthenticateResponse) GetRoles() []*UserOrgRole {
	if x != nil {
		return x.Roles
	}
	return nil
}

type UserOrgRole struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Role          string                 `protobuf:"bytes,1,opt,name=role,proto3" json:"role,omitempty"`
	OrgId         string                 `protobuf:"bytes,2,opt,name=org_id,json=orgId,proto3" json:"org_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UserOrgRole) Reset() {
	*x = UserOrgRole{}
	mi := &file_grpc_auth_authorize_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UserOrgRole) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UserOrgRole) ProtoMessage() {}

func (x *UserOrgRole) ProtoReflect() protoreflect.Message {
	mi := &file_grpc_auth_authorize_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UserOrgRole.ProtoReflect.Descriptor instead.
func (*UserOrgRole) Descriptor() ([]byte, []int) {
	return file_grpc_auth_authorize_proto_rawDescGZIP(), []int{5}
}

func (x *UserOrgRole) GetRole() string {
	if x != nil {
		return x.Role
	}
	return ""
}

func (x *UserOrgRole) GetOrgId() string {
	if x != nil {
		return x.OrgId
	}
	return ""
}

var File_grpc_auth_authorize_proto protoreflect.FileDescriptor

const file_grpc_auth_authorize_proto_rawDesc = "" +
	"\n" +
	"\x19grpc-auth/authorize.proto\"s\n" +
	"\x10AuthorizeRequest\x12\x1a\n" +
	"\bresource\x18\x01 \x01(\tR\bresource\x12\x14\n" +
	"\x05scope\x18\x02 \x01(\tR\x05scope\x12\x16\n" +
	"\x06action\x18\x03 \x01(\tR\x06action\x12\x15\n" +
	"\x06org_id\x18\x04 \x01(\tR\x05orgId\"\\\n" +
	"\x10PermissionDetail\x12\x1a\n" +
	"\bresource\x18\x01 \x01(\tR\bresource\x12\x14\n" +
	"\x05scope\x18\x02 \x01(\tR\x05scope\x12\x16\n" +
	"\x06action\x18\x03 \x01(\tR\x06action\"\\\n" +
	"\x11AuthorizeResponse\x12\x16\n" +
	"\x06result\x18\x01 \x01(\bR\x06result\x12/\n" +
	"\tpermitted\x18\x02 \x01(\v2\x11.PermissionDetailR\tpermitted\"\x15\n" +
	"\x13AuthenticateRequest\"o\n" +
	"\x14AuthenticateResponse\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\tR\x06userId\x12\x1a\n" +
	"\busername\x18\x02 \x01(\tR\busername\x12\"\n" +
	"\x05roles\x18\x03 \x03(\v2\f.UserOrgRoleR\x05roles\"8\n" +
	"\vUserOrgRole\x12\x12\n" +
	"\x04role\x18\x01 \x01(\tR\x04role\x12\x15\n" +
	"\x06org_id\x18\x02 \x01(\tR\x05orgId2{\n" +
	"\x04Auth\x12=\n" +
	"\fAuthenticate\x12\x14.AuthenticateRequest\x1a\x15.AuthenticateResponse\"\x00\x124\n" +
	"\tAuthorize\x12\x11.AuthorizeRequest\x1a\x12.AuthorizeResponse\"\x00B\fZ\n" +
	"grpc-auth/b\x06proto3"

var (
	file_grpc_auth_authorize_proto_rawDescOnce sync.Once
	file_grpc_auth_authorize_proto_rawDescData []byte
)

func file_grpc_auth_authorize_proto_rawDescGZIP() []byte {
	file_grpc_auth_authorize_proto_rawDescOnce.Do(func() {
		file_grpc_auth_authorize_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_grpc_auth_authorize_proto_rawDesc), len(file_grpc_auth_authorize_proto_rawDesc)))
	})
	return file_grpc_auth_authorize_proto_rawDescData
}

var file_grpc_auth_authorize_proto_msgTypes = make([]protoimpl.MessageInfo, 6)
var file_grpc_auth_authorize_proto_goTypes = []any{
	(*AuthorizeRequest)(nil),     // 0: AuthorizeRequest
	(*PermissionDetail)(nil),     // 1: PermissionDetail
	(*AuthorizeResponse)(nil),    // 2: AuthorizeResponse
	(*AuthenticateRequest)(nil),  // 3: AuthenticateRequest
	(*AuthenticateResponse)(nil), // 4: AuthenticateResponse
	(*UserOrgRole)(nil),          // 5: UserOrgRole
}
var file_grpc_auth_authorize_proto_depIdxs = []int32{
	1, // 0: AuthorizeResponse.permitted:type_name -> PermissionDetail
	5, // 1: AuthenticateResponse.roles:type_name -> UserOrgRole
	3, // 2: Auth.Authenticate:input_type -> AuthenticateRequest
	0, // 3: Auth.Authorize:input_type -> AuthorizeRequest
	4, // 4: Auth.Authenticate:output_type -> AuthenticateResponse
	2, // 5: Auth.Authorize:output_type -> AuthorizeResponse
	4, // [4:6] is the sub-list for method output_type
	2, // [2:4] is the sub-list for method input_type
	2, // [2:2] is the sub-list for extension type_name
	2, // [2:2] is the sub-list for extension extendee
	0, // [0:2] is the sub-list for field type_name
}

func init() { file_grpc_auth_authorize_proto_init() }
func file_grpc_auth_authorize_proto_init() {
	if File_grpc_auth_authorize_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_grpc_auth_authorize_proto_rawDesc), len(file_grpc_auth_authorize_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   6,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_grpc_auth_authorize_proto_goTypes,
		DependencyIndexes: file_grpc_auth_authorize_proto_depIdxs,
		MessageInfos:      file_grpc_auth_authorize_proto_msgTypes,
	}.Build()
	File_grpc_auth_authorize_proto = out.File
	file_grpc_auth_authorize_proto_goTypes = nil
	file_grpc_auth_authorize_proto_depIdxs = nil
}
