// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.1
// - protoc             v7.36.1
// source: grpc-auth/entitlements.proto

package grpc_auth

import (
	context "context"

	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	Entitlements_GetEntitlements_FullMethodName      = "/entitlements.v1.Entitlements/GetEntitlements"
	Entitlements_BatchGetEntitlements_FullMethodName = "/entitlements.v1.Entitlements/BatchGetEntitlements"
)

// EntitlementsClient is the client API for Entitlements service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type EntitlementsClient interface {
	// Full entitlement snapshot for one organization.
	GetEntitlements(ctx context.Context, in *GetEntitlementsRequest, opts ...grpc.CallOption) (*OrgEntitlements, error)
	// Snapshots for many organizations, for background jobs. Service callers only.
	BatchGetEntitlements(ctx context.Context, in *BatchGetEntitlementsRequest, opts ...grpc.CallOption) (*BatchGetEntitlementsResponse, error)
}

type entitlementsClient struct {
	cc grpc.ClientConnInterface
}

func NewEntitlementsClient(cc grpc.ClientConnInterface) EntitlementsClient {
	return &entitlementsClient{cc}
}

func (c *entitlementsClient) GetEntitlements(ctx context.Context, in *GetEntitlementsRequest, opts ...grpc.CallOption) (*OrgEntitlements, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(OrgEntitlements)
	err := c.cc.Invoke(ctx, Entitlements_GetEntitlements_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *entitlementsClient) BatchGetEntitlements(ctx context.Context, in *BatchGetEntitlementsRequest, opts ...grpc.CallOption) (*BatchGetEntitlementsResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(BatchGetEntitlementsResponse)
	err := c.cc.Invoke(ctx, Entitlements_BatchGetEntitlements_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// EntitlementsServer is the server API for Entitlements service.
// All implementations must embed UnimplementedEntitlementsServer
// for forward compatibility.
type EntitlementsServer interface {
	// Full entitlement snapshot for one organization.
	GetEntitlements(context.Context, *GetEntitlementsRequest) (*OrgEntitlements, error)
	// Snapshots for many organizations, for background jobs. Service callers only.
	BatchGetEntitlements(context.Context, *BatchGetEntitlementsRequest) (*BatchGetEntitlementsResponse, error)
	mustEmbedUnimplementedEntitlementsServer()
}

// UnimplementedEntitlementsServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedEntitlementsServer struct{}

func (UnimplementedEntitlementsServer) GetEntitlements(context.Context, *GetEntitlementsRequest) (*OrgEntitlements, error) {
	return nil, status.Error(codes.Unimplemented, "method GetEntitlements not implemented")
}
func (UnimplementedEntitlementsServer) BatchGetEntitlements(context.Context, *BatchGetEntitlementsRequest) (*BatchGetEntitlementsResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method BatchGetEntitlements not implemented")
}
func (UnimplementedEntitlementsServer) mustEmbedUnimplementedEntitlementsServer() {}
func (UnimplementedEntitlementsServer) testEmbeddedByValue()                      {}

// UnsafeEntitlementsServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to EntitlementsServer will
// result in compilation errors.
type UnsafeEntitlementsServer interface {
	mustEmbedUnimplementedEntitlementsServer()
}

func RegisterEntitlementsServer(s grpc.ServiceRegistrar, srv EntitlementsServer) {
	// If the following call panics, it indicates UnimplementedEntitlementsServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&Entitlements_ServiceDesc, srv)
}

func _Entitlements_GetEntitlements_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetEntitlementsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(EntitlementsServer).GetEntitlements(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Entitlements_GetEntitlements_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(EntitlementsServer).GetEntitlements(ctx, req.(*GetEntitlementsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Entitlements_BatchGetEntitlements_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(BatchGetEntitlementsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(EntitlementsServer).BatchGetEntitlements(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Entitlements_BatchGetEntitlements_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(EntitlementsServer).BatchGetEntitlements(ctx, req.(*BatchGetEntitlementsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// Entitlements_ServiceDesc is the grpc.ServiceDesc for Entitlements service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var Entitlements_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "entitlements.v1.Entitlements",
	HandlerType: (*EntitlementsServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "GetEntitlements",
			Handler:    _Entitlements_GetEntitlements_Handler,
		},
		{
			MethodName: "BatchGetEntitlements",
			Handler:    _Entitlements_BatchGetEntitlements_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "grpc-auth/entitlements.proto",
}
