// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v7.36.1
// source: grpc-auth/entitlements.proto

package grpc_auth

import (
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"

	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type SubscriptionState int32

const (
	SubscriptionState_SUBSCRIPTION_STATE_UNSPECIFIED SubscriptionState = 0
	// Billing is disabled in this deployment. Nothing is limited.
	SubscriptionState_SUBSCRIPTION_STATE_NOT_MANAGED SubscriptionState = 1
	// Never subscribed, or the first payment never completed.
	SubscriptionState_SUBSCRIPTION_STATE_NONE     SubscriptionState = 2
	SubscriptionState_SUBSCRIPTION_STATE_TRIALING SubscriptionState = 3
	SubscriptionState_SUBSCRIPTION_STATE_ACTIVE   SubscriptionState = 4
	// A renewal payment failed and is being retried. Access continues.
	SubscriptionState_SUBSCRIPTION_STATE_PAST_DUE SubscriptionState = 5
	// Cancelled; access has ended.
	SubscriptionState_SUBSCRIPTION_STATE_CANCELED SubscriptionState = 6
	// Access lapsed for any other reason (unpaid, paused, not renewed).
	SubscriptionState_SUBSCRIPTION_STATE_EXPIRED SubscriptionState = 7
)

// Enum value maps for SubscriptionState.
var (
	SubscriptionState_name = map[int32]string{
		0: "SUBSCRIPTION_STATE_UNSPECIFIED",
		1: "SUBSCRIPTION_STATE_NOT_MANAGED",
		2: "SUBSCRIPTION_STATE_NONE",
		3: "SUBSCRIPTION_STATE_TRIALING",
		4: "SUBSCRIPTION_STATE_ACTIVE",
		5: "SUBSCRIPTION_STATE_PAST_DUE",
		6: "SUBSCRIPTION_STATE_CANCELED",
		7: "SUBSCRIPTION_STATE_EXPIRED",
	}
	SubscriptionState_value = map[string]int32{
		"SUBSCRIPTION_STATE_UNSPECIFIED": 0,
		"SUBSCRIPTION_STATE_NOT_MANAGED": 1,
		"SUBSCRIPTION_STATE_NONE":        2,
		"SUBSCRIPTION_STATE_TRIALING":    3,
		"SUBSCRIPTION_STATE_ACTIVE":      4,
		"SUBSCRIPTION_STATE_PAST_DUE":    5,
		"SUBSCRIPTION_STATE_CANCELED":    6,
		"SUBSCRIPTION_STATE_EXPIRED":     7,
	}
)

func (x SubscriptionState) Enum() *SubscriptionState {
	p := new(SubscriptionState)
	*p = x
	return p
}

func (x SubscriptionState) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (SubscriptionState) Descriptor() protoreflect.EnumDescriptor {
	return file_grpc_auth_entitlements_proto_enumTypes[0].Descriptor()
}

func (SubscriptionState) Type() protoreflect.EnumType {
	return &file_grpc_auth_entitlements_proto_enumTypes[0]
}

func (x SubscriptionState) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use SubscriptionState.Descriptor instead.
func (SubscriptionState) EnumDescriptor() ([]byte, []int) {
	return file_grpc_auth_entitlements_proto_rawDescGZIP(), []int{0}
}

type LimitKind int32

const (
	LimitKind_LIMIT_KIND_UNSPECIFIED LimitKind = 0
	// Standing limit on stored records; never resets.
	LimitKind_LIMIT_KIND_CAP LimitKind = 1
	// Allowance that resets monthly on the billing-cycle day. Count usage
	// within [period_start, period_end).
	LimitKind_LIMIT_KIND_MONTHLY_QUOTA LimitKind = 2
)

// Enum value maps for LimitKind.
var (
	LimitKind_name = map[int32]string{
		0: "LIMIT_KIND_UNSPECIFIED",
		1: "LIMIT_KIND_CAP",
		2: "LIMIT_KIND_MONTHLY_QUOTA",
	}
	LimitKind_value = map[string]int32{
		"LIMIT_KIND_UNSPECIFIED":   0,
		"LIMIT_KIND_CAP":           1,
		"LIMIT_KIND_MONTHLY_QUOTA": 2,
	}
)

func (x LimitKind) Enum() *LimitKind {
	p := new(LimitKind)
	*p = x
	return p
}

func (x LimitKind) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (LimitKind) Descriptor() protoreflect.EnumDescriptor {
	return file_grpc_auth_entitlements_proto_enumTypes[1].Descriptor()
}

func (LimitKind) Type() protoreflect.EnumType {
	return &file_grpc_auth_entitlements_proto_enumTypes[1]
}

func (x LimitKind) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use LimitKind.Descriptor instead.
func (LimitKind) EnumDescriptor() ([]byte, []int) {
	return file_grpc_auth_entitlements_proto_rawDescGZIP(), []int{1}
}

type EntitlementLimit struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	Kind  LimitKind              `protobuf:"varint,1,opt,name=kind,proto3,enum=entitlements.v1.LimitKind" json:"kind,omitempty"`
	// Meaningless when unlimited is true.
	Limit     int64 `protobuf:"varint,2,opt,name=limit,proto3" json:"limit,omitempty"`
	Unlimited bool  `protobuf:"varint,3,opt,name=unlimited,proto3" json:"unlimited,omitempty"`
	// Set only for monthly quotas.
	PeriodStart   *timestamppb.Timestamp `protobuf:"bytes,4,opt,name=period_start,json=periodStart,proto3" json:"period_start,omitempty"`
	PeriodEnd     *timestamppb.Timestamp `protobuf:"bytes,5,opt,name=period_end,json=periodEnd,proto3" json:"period_end,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *EntitlementLimit) Reset() {
	*x = EntitlementLimit{}
	mi := &file_grpc_auth_entitlements_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *EntitlementLimit) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EntitlementLimit) ProtoMessage() {}

func (x *EntitlementLimit) ProtoReflect() protoreflect.Message {
	mi := &file_grpc_auth_entitlements_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EntitlementLimit.ProtoReflect.Descriptor instead.
func (*EntitlementLimit) Descriptor() ([]byte, []int) {
	return file_grpc_auth_entitlements_proto_rawDescGZIP(), []int{0}
}

func (x *EntitlementLimit) GetKind() LimitKind {
	if x != nil {
		return x.Kind
	}
	return LimitKind_LIMIT_KIND_UNSPECIFIED
}

func (x *EntitlementLimit) GetLimit() int64 {
	if x != nil {
		return x.Limit
	}
	return 0
}

func (x *EntitlementLimit) GetUnlimited() bool {
	if x != nil {
		return x.Unlimited
	}
	return false
}

func (x *EntitlementLimit) GetPeriodStart() *timestamppb.Timestamp {
	if x != nil {
		return x.PeriodStart
	}
	return nil
}

func (x *EntitlementLimit) GetPeriodEnd() *timestamppb.Timestamp {
	if x != nil {
		return x.PeriodEnd
	}
	return nil
}

type EntitlementPlan struct {
	state             protoimpl.MessageState `protogen:"open.v1"`
	PriceId           string                 `protobuf:"bytes,1,opt,name=price_id,json=priceId,proto3" json:"price_id,omitempty"`
	Name              string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Tier              string                 `protobuf:"bytes,3,opt,name=tier,proto3" json:"tier,omitempty"`
	Quantity          int64                  `protobuf:"varint,4,opt,name=quantity,proto3" json:"quantity,omitempty"`
	Licenses          int64                  `protobuf:"varint,5,opt,name=licenses,proto3" json:"licenses,omitempty"`
	ProviderStatus    string                 `protobuf:"bytes,6,opt,name=provider_status,json=providerStatus,proto3" json:"provider_status,omitempty"`
	CancelAtPeriodEnd bool                   `protobuf:"varint,7,opt,name=cancel_at_period_end,json=cancelAtPeriodEnd,proto3" json:"cancel_at_period_end,omitempty"`
	CurrentPeriodEnd  *timestamppb.Timestamp `protobuf:"bytes,8,opt,name=current_period_end,json=currentPeriodEnd,proto3" json:"current_period_end,omitempty"`
	unknownFields     protoimpl.UnknownFields
	sizeCache         protoimpl.SizeCache
}

func (x *EntitlementPlan) Reset() {
	*x = EntitlementPlan{}
	mi := &file_grpc_auth_entitlements_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *EntitlementPlan) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EntitlementPlan) ProtoMessage() {}

func (x *EntitlementPlan) ProtoReflect() protoreflect.Message {
	mi := &file_grpc_auth_entitlements_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EntitlementPlan.ProtoReflect.Descriptor instead.
func (*EntitlementPlan) Descriptor() ([]byte, []int) {
	return file_grpc_auth_entitlements_proto_rawDescGZIP(), []int{1}
}

func (x *EntitlementPlan) GetPriceId() string {
	if x != nil {
		return x.PriceId
	}
	return ""
}

func (x *EntitlementPlan) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *EntitlementPlan) GetTier() string {
	if x != nil {
		return x.Tier
	}
	return ""
}

func (x *EntitlementPlan) GetQuantity() int64 {
	if x != nil {
		return x.Quantity
	}
	return 0
}

func (x *EntitlementPlan) GetLicenses() int64 {
	if x != nil {
		return x.Licenses
	}
	return 0
}

func (x *EntitlementPlan) GetProviderStatus() string {
	if x != nil {
		return x.ProviderStatus
	}
	return ""
}

func (x *EntitlementPlan) GetCancelAtPeriodEnd() bool {
	if x != nil {
		return x.CancelAtPeriodEnd
	}
	return false
}

func (x *EntitlementPlan) GetCurrentPeriodEnd() *timestamppb.Timestamp {
	if x != nil {
		return x.CurrentPeriodEnd
	}
	return nil
}

type OrgEntitlements struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	OrgId string                 `protobuf:"bytes,1,opt,name=org_id,json=orgId,proto3" json:"org_id,omitempty"`
	// Whether the organization may use the application at all.
	Entitled bool              `protobuf:"varint,2,opt,name=entitled,proto3" json:"entitled,omitempty"`
	State    SubscriptionState `protobuf:"varint,3,opt,name=state,proto3,enum=entitlements.v1.SubscriptionState" json:"state,omitempty"`
	// Provider's raw status, for display only.
	ProviderStatus string `protobuf:"bytes,4,opt,name=provider_status,json=providerStatus,proto3" json:"provider_status,omitempty"`
	// False when billing is disabled in this deployment. Apply no limits.
	Managed bool `protobuf:"varint,5,opt,name=managed,proto3" json:"managed,omitempty"`
	// False in observe mode: evaluate the rules and log denials, but do not
	// block on them.
	Enforced           bool                   `protobuf:"varint,6,opt,name=enforced,proto3" json:"enforced,omitempty"`
	TrialEndsAt        *timestamppb.Timestamp `protobuf:"bytes,7,opt,name=trial_ends_at,json=trialEndsAt,proto3" json:"trial_ends_at,omitempty"`
	CurrentPeriodStart *timestamppb.Timestamp `protobuf:"bytes,8,opt,name=current_period_start,json=currentPeriodStart,proto3" json:"current_period_start,omitempty"`
	CurrentPeriodEnd   *timestamppb.Timestamp `protobuf:"bytes,9,opt,name=current_period_end,json=currentPeriodEnd,proto3" json:"current_period_end,omitempty"`
	// Set only for the canceled and expired states.
	EndedAt           *timestamppb.Timestamp `protobuf:"bytes,10,opt,name=ended_at,json=endedAt,proto3" json:"ended_at,omitempty"`
	CancelAtPeriodEnd bool                   `protobuf:"varint,11,opt,name=cancel_at_period_end,json=cancelAtPeriodEnd,proto3" json:"cancel_at_period_end,omitempty"`
	Features          []string               `protobuf:"bytes,12,rep,name=features,proto3" json:"features,omitempty"`
	Licenses          int64                  `protobuf:"varint,13,opt,name=licenses,proto3" json:"licenses,omitempty"`
	LicensesUsed      int64                  `protobuf:"varint,14,opt,name=licenses_used,json=licensesUsed,proto3" json:"licenses_used,omitempty"`
	LicensesAvailable int64                  `protobuf:"varint,15,opt,name=licenses_available,json=licensesAvailable,proto3" json:"licenses_available,omitempty"`
	OverLimit         bool                   `protobuf:"varint,16,opt,name=over_limit,json=overLimit,proto3" json:"over_limit,omitempty"`
	// Caps and monthly quotas granted by the plan. A key absent here is not
	// offered on the plan.
	Limits map[string]*EntitlementLimit `protobuf:"bytes,17,rep,name=limits,proto3" json:"limits,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	Plans  []*EntitlementPlan           `protobuf:"bytes,18,rep,name=plans,proto3" json:"plans,omitempty"`
	// When this snapshot was computed; use it to bound how long you cache it.
	ResolvedAt    *timestamppb.Timestamp `protobuf:"bytes,19,opt,name=resolved_at,json=resolvedAt,proto3" json:"resolved_at,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *OrgEntitlements) Reset() {
	*x = OrgEntitlements{}
	mi := &file_grpc_auth_entitlements_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *OrgEntitlements) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*OrgEntitlements) ProtoMessage() {}

func (x *OrgEntitlements) ProtoReflect() protoreflect.Message {
	mi := &file_grpc_auth_entitlements_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use OrgEntitlements.ProtoReflect.Descriptor instead.
func (*OrgEntitlements) Descriptor() ([]byte, []int) {
	return file_grpc_auth_entitlements_proto_rawDescGZIP(), []int{2}
}

func (x *OrgEntitlements) GetOrgId() string {
	if x != nil {
		return x.OrgId
	}
	return ""
}

func (x *OrgEntitlements) GetEntitled() bool {
	if x != nil {
		return x.Entitled
	}
	return false
}

func (x *OrgEntitlements) GetState() SubscriptionState {
	if x != nil {
		return x.State
	}
	return SubscriptionState_SUBSCRIPTION_STATE_UNSPECIFIED
}

func (x *OrgEntitlements) GetProviderStatus() string {
	if x != nil {
		return x.ProviderStatus
	}
	return ""
}

func (x *OrgEntitlements) GetManaged() bool {
	if x != nil {
		return x.Managed
	}
	return false
}

func (x *OrgEntitlements) GetEnforced() bool {
	if x != nil {
		return x.Enforced
	}
	return false
}

func (x *OrgEntitlements) GetTrialEndsAt() *timestamppb.Timestamp {
	if x != nil {
		return x.TrialEndsAt
	}
	return nil
}

func (x *OrgEntitlements) GetCurrentPeriodStart() *timestamppb.Timestamp {
	if x != nil {
		return x.CurrentPeriodStart
	}
	return nil
}

func (x *OrgEntitlements) GetCurrentPeriodEnd() *timestamppb.Timestamp {
	if x != nil {
		return x.CurrentPeriodEnd
	}
	return nil
}

func (x *OrgEntitlements) GetEndedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.EndedAt
	}
	return nil
}

func (x *OrgEntitlements) GetCancelAtPeriodEnd() bool {
	if x != nil {
		return x.CancelAtPeriodEnd
	}
	return false
}

func (x *OrgEntitlements) GetFeatures() []string {
	if x != nil {
		return x.Features
	}
	return nil
}

func (x *OrgEntitlements) GetLicenses() int64 {
	if x != nil {
		return x.Licenses
	}
	return 0
}

func (x *OrgEntitlements) GetLicensesUsed() int64 {
	if x != nil {
		return x.LicensesUsed
	}
	return 0
}

func (x *OrgEntitlements) GetLicensesAvailable() int64 {
	if x != nil {
		return x.LicensesAvailable
	}
	return 0
}

func (x *OrgEntitlements) GetOverLimit() bool {
	if x != nil {
		return x.OverLimit
	}
	return false
}

func (x *OrgEntitlements) GetLimits() map[string]*EntitlementLimit {
	if x != nil {
		return x.Limits
	}
	return nil
}

func (x *OrgEntitlements) GetPlans() []*EntitlementPlan {
	if x != nil {
		return x.Plans
	}
	return nil
}

func (x *OrgEntitlements) GetResolvedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.ResolvedAt
	}
	return nil
}

type GetEntitlementsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	OrgId         string                 `protobuf:"bytes,1,opt,name=org_id,json=orgId,proto3" json:"org_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetEntitlementsRequest) Reset() {
	*x = GetEntitlementsRequest{}
	mi := &file_grpc_auth_entitlements_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetEntitlementsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetEntitlementsRequest) ProtoMessage() {}

func (x *GetEntitlementsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_grpc_auth_entitlements_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetEntitlementsRequest.ProtoReflect.Descriptor instead.
func (*GetEntitlementsRequest) Descriptor() ([]byte, []int) {
	return file_grpc_auth_entitlements_proto_rawDescGZIP(), []int{3}
}

func (x *GetEntitlementsRequest) GetOrgId() string {
	if x != nil {
		return x.OrgId
	}
	return ""
}

type BatchGetEntitlementsRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// At most 100 organizations. Service callers only.
	OrgIds        []string `protobuf:"bytes,1,rep,name=org_ids,json=orgIds,proto3" json:"org_ids,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *BatchGetEntitlementsRequest) Reset() {
	*x = BatchGetEntitlementsRequest{}
	mi := &file_grpc_auth_entitlements_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BatchGetEntitlementsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BatchGetEntitlementsRequest) ProtoMessage() {}

func (x *BatchGetEntitlementsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_grpc_auth_entitlements_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BatchGetEntitlementsRequest.ProtoReflect.Descriptor instead.
func (*BatchGetEntitlementsRequest) Descriptor() ([]byte, []int) {
	return file_grpc_auth_entitlements_proto_rawDescGZIP(), []int{4}
}

func (x *BatchGetEntitlementsRequest) GetOrgIds() []string {
	if x != nil {
		return x.OrgIds
	}
	return nil
}

type BatchGetEntitlementsResponse struct {
	state         protoimpl.MessageState      `protogen:"open.v1"`
	Entitlements  map[string]*OrgEntitlements `protobuf:"bytes,1,rep,name=entitlements,proto3" json:"entitlements,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *BatchGetEntitlementsResponse) Reset() {
	*x = BatchGetEntitlementsResponse{}
	mi := &file_grpc_auth_entitlements_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BatchGetEntitlementsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BatchGetEntitlementsResponse) ProtoMessage() {}

func (x *BatchGetEntitlementsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_grpc_auth_entitlements_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BatchGetEntitlementsResponse.ProtoReflect.Descriptor instead.
func (*BatchGetEntitlementsResponse) Descriptor() ([]byte, []int) {
	return file_grpc_auth_entitlements_proto_rawDescGZIP(), []int{5}
}

func (x *BatchGetEntitlementsResponse) GetEntitlements() map[string]*OrgEntitlements {
	if x != nil {
		return x.Entitlements
	}
	return nil
}

var File_grpc_auth_entitlements_proto protoreflect.FileDescriptor

const file_grpc_auth_entitlements_proto_rawDesc = "" +
	"\n" +
	"\x1cgrpc-auth/entitlements.proto\x12\x0fentitlements.v1\x1a\x1fgoogle/protobuf/timestamp.proto\"\xf0\x01\n" +
	"\x10EntitlementLimit\x12.\n" +
	"\x04kind\x18\x01 \x01(\x0e2\x1a.entitlements.v1.LimitKindR\x04kind\x12\x14\n" +
	"\x05limit\x18\x02 \x01(\x03R\x05limit\x12\x1c\n" +
	"\tunlimited\x18\x03 \x01(\bR\tunlimited\x12=\n" +
	"\fperiod_start\x18\x04 \x01(\v2\x1a.google.protobuf.TimestampR\vperiodStart\x129\n" +
	"\n" +
	"period_end\x18\x05 \x01(\v2\x1a.google.protobuf.TimestampR\tperiodEnd\"\xb0\x02\n" +
	"\x0fEntitlementPlan\x12\x19\n" +
	"\bprice_id\x18\x01 \x01(\tR\apriceId\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x12\x12\n" +
	"\x04tier\x18\x03 \x01(\tR\x04tier\x12\x1a\n" +
	"\bquantity\x18\x04 \x01(\x03R\bquantity\x12\x1a\n" +
	"\blicenses\x18\x05 \x01(\x03R\blicenses\x12'\n" +
	"\x0fprovider_status\x18\x06 \x01(\tR\x0eproviderStatus\x12/\n" +
	"\x14cancel_at_period_end\x18\a \x01(\bR\x11cancelAtPeriodEnd\x12H\n" +
	"\x12current_period_end\x18\b \x01(\v2\x1a.google.protobuf.TimestampR\x10currentPeriodEnd\"\xe1\a\n" +
	"\x0fOrgEntitlements\x12\x15\n" +
	"\x06org_id\x18\x01 \x01(\tR\x05orgId\x12\x1a\n" +
	"\bentitled\x18\x02 \x01(\bR\bentitled\x128\n" +
	"\x05state\x18\x03 \x01(\x0e2\".entitlements.v1.SubscriptionStateR\x05state\x12'\n" +
	"\x0fprovider_status\x18\x04 \x01(\tR\x0eproviderStatus\x12\x18\n" +
	"\amanaged\x18\x05 \x01(\bR\amanaged\x12\x1a\n" +
	"\benforced\x18\x06 \x01(\bR\benforced\x12>\n" +
	"\rtrial_ends_at\x18\a \x01(\v2\x1a.google.protobuf.TimestampR\vtrialEndsAt\x12L\n" +
	"\x14current_period_start\x18\b \x01(\v2\x1a.google.protobuf.TimestampR\x12currentPeriodStart\x12H\n" +
	"\x12current_period_end\x18\t \x01(\v2\x1a.google.protobuf.TimestampR\x10currentPeriodEnd\x125\n" +
	"\bended_at\x18\n" +
	" \x01(\v2\x1a.google.protobuf.TimestampR\aendedAt\x12/\n" +
	"\x14cancel_at_period_end\x18\v \x01(\bR\x11cancelAtPeriodEnd\x12\x1a\n" +
	"\bfeatures\x18\f \x03(\tR\bfeatures\x12\x1a\n" +
	"\blicenses\x18\r \x01(\x03R\blicenses\x12#\n" +
	"\rlicenses_used\x18\x0e \x01(\x03R\flicensesUsed\x12-\n" +
	"\x12licenses_available\x18\x0f \x01(\x03R\x11licensesAvailable\x12\x1d\n" +
	"\n" +
	"over_limit\x18\x10 \x01(\bR\toverLimit\x12D\n" +
	"\x06limits\x18\x11 \x03(\v2,.entitlements.v1.OrgEntitlements.LimitsEntryR\x06limits\x126\n" +
	"\x05plans\x18\x12 \x03(\v2 .entitlements.v1.EntitlementPlanR\x05plans\x12;\n" +
	"\vresolved_at\x18\x13 \x01(\v2\x1a.google.protobuf.TimestampR\n" +
	"resolvedAt\x1a\\\n" +
	"\vLimitsEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x127\n" +
	"\x05value\x18\x02 \x01(\v2!.entitlements.v1.EntitlementLimitR\x05value:\x028\x01\"/\n" +
	"\x16GetEntitlementsRequest\x12\x15\n" +
	"\x06org_id\x18\x01 \x01(\tR\x05orgId\"6\n" +
	"\x1bBatchGetEntitlementsRequest\x12\x17\n" +
	"\aorg_ids\x18\x01 \x03(\tR\x06orgIds\"\xe6\x01\n" +
	"\x1cBatchGetEntitlementsResponse\x12c\n" +
	"\fentitlements\x18\x01 \x03(\v2?.entitlements.v1.BatchGetEntitlementsResponse.EntitlementsEntryR\fentitlements\x1aa\n" +
	"\x11EntitlementsEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x126\n" +
	"\x05value\x18\x02 \x01(\v2 .entitlements.v1.OrgEntitlementsR\x05value:\x028\x01*\x9a\x02\n" +
	"\x11SubscriptionState\x12\"\n" +
	"\x1eSUBSCRIPTION_STATE_UNSPECIFIED\x10\x00\x12\"\n" +
	"\x1eSUBSCRIPTION_STATE_NOT_MANAGED\x10\x01\x12\x1b\n" +
	"\x17SUBSCRIPTION_STATE_NONE\x10\x02\x12\x1f\n" +
	"\x1bSUBSCRIPTION_STATE_TRIALING\x10\x03\x12\x1d\n" +
	"\x19SUBSCRIPTION_STATE_ACTIVE\x10\x04\x12\x1f\n" +
	"\x1bSUBSCRIPTION_STATE_PAST_DUE\x10\x05\x12\x1f\n" +
	"\x1bSUBSCRIPTION_STATE_CANCELED\x10\x06\x12\x1e\n" +
	"\x1aSUBSCRIPTION_STATE_EXPIRED\x10\a*Y\n" +
	"\tLimitKind\x12\x1a\n" +
	"\x16LIMIT_KIND_UNSPECIFIED\x10\x00\x12\x12\n" +
	"\x0eLIMIT_KIND_CAP\x10\x01\x12\x1c\n" +
	"\x18LIMIT_KIND_MONTHLY_QUOTA\x10\x022\xe5\x01\n" +
	"\fEntitlements\x12^\n" +
	"\x0fGetEntitlements\x12'.entitlements.v1.GetEntitlementsRequest\x1a .entitlements.v1.OrgEntitlements\"\x00\x12u\n" +
	"\x14BatchGetEntitlements\x12,.entitlements.v1.BatchGetEntitlementsRequest\x1a-.entitlements.v1.BatchGetEntitlementsResponse\"\x00B\fZ\n" +
	"grpc-auth/b\x06proto3"

var (
	file_grpc_auth_entitlements_proto_rawDescOnce sync.Once
	file_grpc_auth_entitlements_proto_rawDescData []byte
)

func file_grpc_auth_entitlements_proto_rawDescGZIP() []byte {
	file_grpc_auth_entitlements_proto_rawDescOnce.Do(func() {
		file_grpc_auth_entitlements_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_grpc_auth_entitlements_proto_rawDesc), len(file_grpc_auth_entitlements_proto_rawDesc)))
	})
	return file_grpc_auth_entitlements_proto_rawDescData
}

var file_grpc_auth_entitlements_proto_enumTypes = make([]protoimpl.EnumInfo, 2)
var file_grpc_auth_entitlements_proto_msgTypes = make([]protoimpl.MessageInfo, 8)
var file_grpc_auth_entitlements_proto_goTypes = []any{
	(SubscriptionState)(0),               // 0: entitlements.v1.SubscriptionState
	(LimitKind)(0),                       // 1: entitlements.v1.LimitKind
	(*EntitlementLimit)(nil),             // 2: entitlements.v1.EntitlementLimit
	(*EntitlementPlan)(nil),              // 3: entitlements.v1.EntitlementPlan
	(*OrgEntitlements)(nil),              // 4: entitlements.v1.OrgEntitlements
	(*GetEntitlementsRequest)(nil),       // 5: entitlements.v1.GetEntitlementsRequest
	(*BatchGetEntitlementsRequest)(nil),  // 6: entitlements.v1.BatchGetEntitlementsRequest
	(*BatchGetEntitlementsResponse)(nil), // 7: entitlements.v1.BatchGetEntitlementsResponse
	nil,                                  // 8: entitlements.v1.OrgEntitlements.LimitsEntry
	nil,                                  // 9: entitlements.v1.BatchGetEntitlementsResponse.EntitlementsEntry
	(*timestamppb.Timestamp)(nil),        // 10: google.protobuf.Timestamp
}
var file_grpc_auth_entitlements_proto_depIdxs = []int32{
	1,  // 0: entitlements.v1.EntitlementLimit.kind:type_name -> entitlements.v1.LimitKind
	10, // 1: entitlements.v1.EntitlementLimit.period_start:type_name -> google.protobuf.Timestamp
	10, // 2: entitlements.v1.EntitlementLimit.period_end:type_name -> google.protobuf.Timestamp
	10, // 3: entitlements.v1.EntitlementPlan.current_period_end:type_name -> google.protobuf.Timestamp
	0,  // 4: entitlements.v1.OrgEntitlements.state:type_name -> entitlements.v1.SubscriptionState
	10, // 5: entitlements.v1.OrgEntitlements.trial_ends_at:type_name -> google.protobuf.Timestamp
	10, // 6: entitlements.v1.OrgEntitlements.current_period_start:type_name -> google.protobuf.Timestamp
	10, // 7: entitlements.v1.OrgEntitlements.current_period_end:type_name -> google.protobuf.Timestamp
	10, // 8: entitlements.v1.OrgEntitlements.ended_at:type_name -> google.protobuf.Timestamp
	8,  // 9: entitlements.v1.OrgEntitlements.limits:type_name -> entitlements.v1.OrgEntitlements.LimitsEntry
	3,  // 10: entitlements.v1.OrgEntitlements.plans:type_name -> entitlements.v1.EntitlementPlan
	10, // 11: entitlements.v1.OrgEntitlements.resolved_at:type_name -> google.protobuf.Timestamp
	9,  // 12: entitlements.v1.BatchGetEntitlementsResponse.entitlements:type_name -> entitlements.v1.BatchGetEntitlementsResponse.EntitlementsEntry
	2,  // 13: entitlements.v1.OrgEntitlements.LimitsEntry.value:type_name -> entitlements.v1.EntitlementLimit
	4,  // 14: entitlements.v1.BatchGetEntitlementsResponse.EntitlementsEntry.value:type_name -> entitlements.v1.OrgEntitlements
	5,  // 15: entitlements.v1.Entitlements.GetEntitlements:input_type -> entitlements.v1.GetEntitlementsRequest
	6,  // 16: entitlements.v1.Entitlements.BatchGetEntitlements:input_type -> entitlements.v1.BatchGetEntitlementsRequest
	4,  // 17: entitlements.v1.Entitlements.GetEntitlements:output_type -> entitlements.v1.OrgEntitlements
	7,  // 18: entitlements.v1.Entitlements.BatchGetEntitlements:output_type -> entitlements.v1.BatchGetEntitlementsResponse
	17, // [17:19] is the sub-list for method output_type
	15, // [15:17] is the sub-list for method input_type
	15, // [15:15] is the sub-list for extension type_name
	15, // [15:15] is the sub-list for extension extendee
	0,  // [0:15] is the sub-list for field type_name
}

func init() { file_grpc_auth_entitlements_proto_init() }
func file_grpc_auth_entitlements_proto_init() {
	if File_grpc_auth_entitlements_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_grpc_auth_entitlements_proto_rawDesc), len(file_grpc_auth_entitlements_proto_rawDesc)),
			NumEnums:      2,
			NumMessages:   8,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_grpc_auth_entitlements_proto_goTypes,
		DependencyIndexes: file_grpc_auth_entitlements_proto_depIdxs,
		EnumInfos:         file_grpc_auth_entitlements_proto_enumTypes,
		MessageInfos:      file_grpc_auth_entitlements_proto_msgTypes,
	}.Build()
	File_grpc_auth_entitlements_proto = out.File
	file_grpc_auth_entitlements_proto_goTypes = nil
	file_grpc_auth_entitlements_proto_depIdxs = nil
}
