name: Auto-approve Renovate PRs

on:
  pull_request:
    types: [opened, synchronize, reopened]

permissions:
  contents: write
  pull-requests: write
  checks: read
  actions: read

jobs:
  auto-approve:
    runs-on: ubuntu-latest
    timeout-minutes: 30
    # Only target safe updates from Renovate
    if: >
      github.event.pull_request.user.login == 'renovate[bot]' &&
      (startsWith(github.event.pull_request.title, 'fix(deps):') ||
       startsWith(github.event.pull_request.title, 'chore(deps):') ||
       startsWith(github.event.pull_request.title, 'chore(deps-dev):') ||
       (startsWith(github.event.pull_request.title, 'Update ') &&
        !contains(github.event.pull_request.title, 'major')))
    steps:
      - name: Checkout repository
        uses: actions/checkout@v5

      # CRUCIAL: Wait for CI checks to complete first
      - name: Wait for CI checks to complete
        uses: lewagon/wait-on-check-action@v1.4.1
        with:
          ref: ${{ github.event.pull_request.head.sha }}
          repo-token: ${{ secrets.GITHUB_TOKEN }}
          wait-interval: 30
          running-workflow-name: 'auto-approve'

      # Only approve if CI passes
      - name: Approve PR and enable auto-merge
        if: success()
        run: |
          # Approve the PR
          gh pr review --approve ${{ github.event.pull_request.number }}
          # Enable auto-merge
          gh pr merge --auto --merge ${{ github.event.pull_request.number }}
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
